language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: lint, test and build
      name: commitlint
      script: npm run commitlint
    - name: test
      script:
        - npm test -- --ci --coverage
        - npm run coveralls
    - name: build
      script: npm run build
    - stage: deploy
      script:
        - git remote set-url origin git@github.com:iamogbz/webpack-compiler-plugin.git --push
        - npm run build && npm run release
      if: branch = master
